apiVersion: v1alpha1
sts-region: us-east-1
discovery:
  exportedTagsOnMetrics:
    AWS/EC2:
      - Environment
    AWS/Lambda:
      - Environment
  jobs:
    - type: AWS/EC2
      regions: 
        - eu-north-1
      metrics:
        - name: CPUUtilization
        - name: NetworkIn
        - name: NetworkOut
        - name: EBSReadOps
        - name: EBSWriteOps
      dimensionNameRequirements:
        - InstanceId
      includeContextOnInfoMetrics: true
      statistics:
        - Average
      period: 300
      length: 300
    - type: AWS/Lambda
      regions: 
        - eu-north-1
      metrics:
        - name: Invocations
          statistics: [Sum]
        - name: Errors
          statistics: [Sum]
        - name: Throttles
          statistics: [Sum]
        - name: Duration
          statistics: [Average, Maximum, Minimum, p90]
      dimensionNameRequirements:
        - FunctionName
      includeContextOnInfoMetrics: true
      statistics:
        - Average
      period: 300
      length: 300