apiVersion: v1alpha1
discovery:
  exportedTagsOnMetrics:
    AWS/EC2:
      - Environment
    AWS/Lambda:
      - Environment
  jobs:
    - type: AWS/EC2
      roles:
        - arn:aws:iam::12345678912:role/org-observability
      regions: 
        - eu-north-1
      metrics:
        - name: CPUUtilization
        - name: NetworkIn
        - name: NetworkOut
        - name: EBSReadOps
        - name: EBSWriteOps
      dimensionNameRequirements:
        - InstanceId
      includeContextOnInfoMetrics: true
      statistics:
        - Average
      period: 300
      length: 300
